### ISSUE TITLE
HandleShortcut callback not called

### ISSUE THREAD

**Issue by Andarius** [lokyoung/react-native-app-shortcuts#8]
**React**
16.3.0

**React Native**
0.54.4

I'm trying to get RNAppShortcuts.handleShortcut to work with
```
componentWillMount() {
  RNAppShortcuts.addShortcut({
     id: '1',
    shortLabel: 'test',
    longLabel: 'test 1',
    iconFolderName: 'drawable',
    iconName: 'icon'})

    RNAppShortcuts.handleShortcut((id) => {
            console.log('Received id: ', id)
    })
 }
```
But I never see the logs once clicking on the shortcut. Any idea why ?

**Comment by fredikey** [comment]
Same issue on RN 0.54.4

**Comment by felipeM0-zz** [comment]
> **React**
> 16.3.0
> 
> **React Native**
> 0.54.4
> 
> I'm trying to get RNAppShortcuts.handleShortcut to work with
> 
> ```
> componentWillMount() {
>   RNAppShortcuts.addShortcut({
>      id: '1',
>     shortLabel: 'test',
>     longLabel: 'test 1',
>     iconFolderName: 'drawable',
>     iconName: 'icon'})
> 
>     RNAppShortcuts.handleShortcut((id) => {
>             console.log('Received id: ', id)
>     })
>  }
> ```
> 
> But I never see the logs once clicking on the shortcut. Any idea why ?

I had the same problem, so i faithfully followed the documentation and used "function" when calling the handle and it worked.

```
RNAppShortcuts.handleShortcut(function(id) {
       console.log('Received id: ', id)
})
```

I hope to help!
